version: '2'
services:
  cars:
    image: pravinba/cars
    container_name: cars-app
    ports:
        - 8080:8080
    
    depends_on:
        - carsdb
        

  insurance:
    image: pravinba/insurance
    container_name: insurance-app
    ports:
        - 8081:8081
    
    depends_on:
        - insurancedb
            
  carsdb:
    image: mysql
    container_name: carsdb-mysql
    ports:
        - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: carsdb
    
  insurancedb:
    image: mysql
    container_name: insurancedb-mysql
    ports:
        - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: insurancedb  
    



