spring:
    profiles: container
  
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://mysql:3306/carsdb
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
        