spring:
    profiles: container
  
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://insurancedb:3306/insurancedb
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
server: 
  port: 8081
  